# CONFIG_PMW3610_SWAP_XY=y
# CONFIG_PMW3610_INVERT_X=y
# CONFIG_PMW3610_INVERT_Y=n
# CONFIG_PMW3610_SMART_ALGORITHM=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=n

CONFIG_ZMK_SLEEP=y

# CONFIG_RGBLED_WIDGET=y
# CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=n
# CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
